name: EBAC CI Mobile

on:
  push:
    branches: [ ci ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Set environment variable to skip Chromedriver install
        run: echo "APPIUM_SKIP_CHROMEDRIVER_INSTALL=true" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        run: npm test
      
      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report
          npx allure open allure-report
      
      - name: Publish Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
